services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: books
    ports:
      - 5433:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
      
  app:
    build: .
    container_name: book-management-dev
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db_data:
  node_modules:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./node_modules