openapi: 3.0.0
info:
  title: Book Management API
  version: 1.0.0
  description: API documentation for Book Management service

servers:
  - url: http://localhost:3000

paths:
  /books:
    $ref: './paths/books.yaml'
  /books/{id}:
    $ref: './paths/booksById.yaml'
  /auth/register:
    $ref: './paths/authRegister.yaml'
  /auth/login:
    $ref: './paths/authLogin.yaml'

components:
  schemas:
    Book:
      $ref: './components/schemas/Book.yaml'
    User:
      $ref: './components/schemas/User.yaml'

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []
